name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore src/EventSourcingOnAzureFunctions.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src/EventSourcingOnAzureFunctions.sln
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal src/EventSourcingOnAzureFunctions.sln
    - name: Generate NuGet package
      run: dotnet pack  --no-build -c Release src/EventSourcingOnAzureFunctions.Common/EventSourcingOnAzureFunctions.Common.csproj -o src/EventSourcingOnAzureFunctions.Common
    - name: Publish EventSourcingOnAzureFunctions.Common
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: src/EventSourcingOnAzureFunctions.Common/EventSourcingOnAzureFunctions.Common.csproj
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          INCLUDE_SYMBOLS: true
