name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore src/EventSourcingOnAzureFunctions.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src/EventSourcingOnAzureFunctions.sln
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal src/EventSourcingOnAzureFunctions.sln
    - name : Nuget package
      run: nuget pack src/EventSourcingOnAzureFunctions.Common/EventSourcingOnAzureFunctions.Common.nuspec
    - name : Nuget push
      run: dotnet nuget push -s src/EventSourcingOnAzureFunctions.Common.1.1.0.nupkg -k ${{secrets.NUGET_API_KEY}} 
