name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore src/EventSourcingOnAzureFunctions.sln
    - name: Build
      run: dotnet build --no-restore src/EventSourcingOnAzureFunctions.sln
    - name: Test
      run: dotnet test --no-build --verbosity normal src/EventSourcingOnAzureFunctions.sln
    - name: Publish common library to NuGet
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
        PROJECT_FILE_PATH: src/EventSourcingOnAzureFunctions.Common/EventSourcingOnAzureFunctions.Common.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
        VERSION_STATIC: 1.0.1
