name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore src/EventSourcingOnAzureFunctions.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src/EventSourcingOnAzureFunctions.sln
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal src/EventSourcingOnAzureFunctions.sln
    - name : Nuget package
      run: dotnet pack --configuration Release --no-build --verbosity normal src/EventSourcingOnAzureFunctions.Common/EventSourcingOnAzureFunctions.Common.csproj
    - name: Publish common library to NuGet
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/EventSourcingOnAzureFunctions.Common/EventSourcingOnAzureFunctions.Common.csproj
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
        INCLUDE_SYMBOLS: true
        PACKAGE_NAME: EventSourcingOnAzureFunctions.Common
        VERSION_STATIC: 1.1.0
