name: .NET

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Restore dependencies
      run: dotnet restore src/EventSourcingOnAzureFunctions.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore src/EventSourcingOnAzureFunctions.sln
    - name: Test
      run: dotnet test --configuration Release --no-build --verbosity normal src/EventSourcingOnAzureFunctions.sln
    - name: Generate NuGet package
      run: dotnet pack --no-build -c --include-source Release src/EventSourcingOnAzureFunctions.Common/EventSourcingOnAzureFunctions.Common.csproj -o src/EventSourcingOnAzureFunctions.Common
    - name: Push NuGet package
      run: dotnet nuget push src/EventSourcingOnAzureFunctions.Common/EventSourcingOnAzureFunctions.Common.nupkg -s https://api.nuget.org/v3/index.json -k ${{ NUGET_KEY }}  --skip-duplicate
